services:
  app:
    container_name: smartcar-api
    build:
      context: .
      dockerfile: Dockerfile.local
    command: pnpm start
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
